version: "1.0"
services:
  xai-law:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER: ${USER}
        USER_PW: ${USER_PW}
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: "${ENVIRONMENT}-xai-law"
    entrypoint: bash /docker-entrypoint.sh
    environment:
      - TZ=Asia/Seoul
    shm_size: 2gb
    expose:
      - "22"
    ports:
      - "${SSH_PORT}:22"
      - "${WEB_PORT}:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    volumes:
        - ../:/root/XAI_Jeongguan
    working_dir: /root/XAI_Jeongguan
